### ISSUE TITLE
IPv6-only VM provisioning gets stuck at "wait_sshable" if the respirate's host doesn't support IPv6

### ISSUE THREAD

**Issue by enescakir** [ubicloud/ubicloud#1073]
Our control plane is currently deployed to Heroku. We verify SSH connectivity at the `wait_sshable` label during the provisioning of a new VM. These SSH connections are initiated from the respirate. Therefore, if the VM is IPv6-only, the respirate requires IPv6 networking to reach the VM. However, it appears that Heroku does not support IPv6. Even though the IPv6-only VM is up and running, the VM's nexus cannot hop from the `wait_sshable` label. The VM is constantly displayed as 'creating' on the UI.

We haven't yet decided how to solve this issue. Possible solutions include:

1. **Deploy our control plane to another provider**: The major migration destination is Ubicloud :D. It's good to serve Ubicloud on Ubicloud. However, we haven't reached that point yet.

2. **Skip "wait_sshable" for IPv6-only VM**: This is not a real solution. This will only unblock IPv6-only VM provisioning, and the VM will appear as "running" in the UI. However, we cannot confirm whether the VM has actually booted.

3. **Replace "wait_sshable" something robust**: @byucesoy is working on monitoring architecture https://github.com/ubicloud/ubicloud/pull/1029. We can more reliably check the health of the VM with the new architecture. We should consider verifying SSH connectivity through the VM host.

**Comment by fdr** [comment]
I chose option 2, the not a real solution, because 100% failure rate with unistack was no bueno #1170
