### ISSUE TITLE
Improve project invitation and user verification emails

### ISSUE THREAD

**Issue by ozgune** [ubicloud/ubicloud#1133]
We received feedback about improving Ubicloud's project invitation and user verification emails.

1. Today, these invitation emails have their reply-to (and sender) fields set to daniel@ubicloud.com. We should probably at least change the reply-to email field to an alias like info or support@.
2. Today, these emails have a button to "Verify Account" or "Join Project". These buttons' width is too big (looks like due to border width). Change these button widths to a more reasonable size. Screenshot attached.

![Screenshot 2024-01-18 at 4 42 17 PM](https://github.com/ubicloud/ubicloud/assets/2545443/4cb27f3f-2d47-44b8-b139-e6c23c6e2ad2)

**Comment by ozgune** [comment]
I'm assigning this issue to @enescakir since he's our UI expert. Enes, please consider this issue as lower priority than the ones that are currently in your plate. This is primarily in case you have spare time.

**Comment by enescakir** [comment]
We fixed them.
