### ISSUE TITLE
Project names can't be renamed in the Ubicloud console. This leads to confusion

### ISSUE THREAD

**Issue by ozgune** [ubicloud/ubicloud#1134]
We received feedback from a user about project names in the Ubicloud console.

In the ubicloud console, looks like the default project can't be renamed from the "default" (or at least, I wasn't able to find how to rename). Since I'm invited to a coworker's default project, the console looks very confusing as there are two default projects and I don't see clear way to distinguish between them.

<img width="1025" alt="Screenshot 2024-01-18 at 4 48 14 PM" src="https://github.com/ubicloud/ubicloud/assets/2545443/f4fdff2c-d9f3-4476-bf61-5dab4ddd9937">

**Comment by enescakir** [comment]
Fixed with https://github.com/ubicloud/ubicloud/pull/1182
