### ISSUE TITLE
ip link add command fails on the second attempt

### ISSUE THREAD

**Issue by enescakir** [ubicloud/ubicloud#1142]
When the prep script failed for a reason, the second attempt also failed, producing the following error. However, the third attempt was successful. Therefore, it's not stuck, but it requires an additional retry.

```
/home/rhizome/common/lib/util.rb:28:in `r': command failed: ip link add vethovmz47x4h addr 2a:5c:57:ac:18:e4 type veth peer name vethivmz47x4h addr 42:54:08:03:58:22 netns vmz47x4h (CommandFail)

---STDOUT---


---STDERR---
RTNETLINK answers: File exists
        from /home/rhizome/host/lib/vm_setup.rb:154:in `interfaces'
        from /home/rhizome/host/lib/vm_setup.rb:78:in `setup_networking'
        from /home/rhizome/host/lib/vm_setup.rb:47:in `prep'
        from host/bin/prepvm.rb:90:in `<main>'
```

**Comment by enescakir** [comment]
We rebooted a vm host that has  a number of these VMs were in `create_unix_user`. These did not reboot properly, due to an idempotency bug. The failed command similar to this one.

```
/home/rhizome/common/lib/util.rb:28:in `r': command failed: ip link add vethovmxxb7qh addr 56:bb:66:be:ba:44 type veth peer name vethivmxxb7qh addr e6:d1:fe:0f:94:bb netns vmxxb7qh (CommandFail)

---STDOUT---


---STDERR---
RTNETLINK answers: File exists
from /home/rhizome/host/lib/vm_setup.rb:187:in `interfaces'
from /home/rhizome/host/lib/vm_setup.rb:79:in `setup_networking'
from /home/rhizome/host/lib/vm_setup.rb:56:in `recreate_unpersisted'
from host/bin/recreate-unpersisted:66:in `<main>'
{"ssh":{"start":"2024-03-22 17:57:00 +0000","finish":"2024-03-22 17:57:01 +0000","duration":0.679466053,"cmd":"sudo host/bin/recreate-unpersisted /vm/vmxxb7qh/prep.json","exit_code":1,"exit_signal":null},"message":"ssh cmd execution","time":"2024-03-22 17:57:01 +0000"}
```

**Comment by furkansahin** [comment]
Alright, it was difficult to figure out how come the interface wouldn't be deleted when the namespace is deleted but I could reproduce the issue. Apparently, when there is an active process, running inside the namespace, even if we send delete and it succeeds, the interface is not removed until the process clears up. I could reproduce it simply sleeping inside the namespace. Here is the fix PR https://github.com/ubicloud/ubicloud/pull/1385
