### ISSUE TITLE
When a strand has children more than Config.db_pool, the respirate might stuck

### ISSUE THREAD

**Issue by enescakir** [ubicloud/ubicloud#1149]
The dispatcher retrieves a list of unleased and scheduled strands.

https://github.com/ubicloud/ubicloud/blob/46e2647d69f11914214771c2be71bf9900d97b8d/scheduling/dispatcher.rb#L21

When the strand attempts to take a lease, it ensures that it's not already leased or scheduled. It also verifies that it doesn't have an exit value.

https://github.com/ubicloud/ubicloud/blob/46e2647d69f11914214771c2be71bf9900d97b8d/model/strand.rb#L26

The divergence in the conditions of these queries may cause the respirate stuck.

Imagine we have a parent strand with 8 child strands, but the `Config.db_pool` value is only 5. If all the children have an exit value, and the first query selects 5 child strands with exit values, it cannot lease any of them due to their exit value. If the first query doesn't return the parent strand, which should reap the child strands, at any time; the respirate stalls because it cannot lease the exited children.

Increasing the `Config.db_pool` value to higher than the maximum number of budded child strands can resolve the issue. However, this is not a complete solution as the maximum budded child count may increase over time.

I believe the proper solution is to add an `exitval` condition to the first query as well.

**Comment by fdr** [comment]
Good find. I had to think about it for a moment until I grokked it fully.

**Comment by fdr** [comment]
I think the child count is more correlated than causal (any unlucky distribution of return values that is all exited strands causes the fault), should be fixed using your suggestion in d1e74db72793afeeb2da47174b88575d9f020bae (sorry I didn't credit you here, I goofed)
