### ISSUE TITLE
Question about Ubicloud Github Runners

### ISSUE THREAD

**Issue by RudyD** [ubicloud/ubicloud#1165]
If I choose to use ubicloud as a mechanism to host GitHub runners, as advertised in https://www.ubicloud.com/use-cases/github-actions, are these runners enabled with GPUs? What are the hardware specs for the runners? Any more details you can provide beyond the advertised link would be helpful as I would like to use runners to execute machine learning jobs.

**Comment by byucesoy** [comment]
Hi @RudyD. These runners are not GPU enabled. We are considering offering VMs (not runners, but the work we would do can be extended to runners as well based on demand) with GPU in the long run but right now it is not in our immediate plans.

I'm closing this issue as we primarily use issues section for bugs/improvements. If you have any other questions, feel free to post them to the [discussions](https://github.com/ubicloud/ubicloud/discussions).
