### ISSUE TITLE
While adding VmHost, selecting Location&Provider confuses first timers

### ISSUE THREAD

**Issue by enescakir** [ubicloud/ubicloud#137]
While adding VmHost, Location&Provider fields helps to associate VmHost with that location. So Vm allocation algorithm can select that VmHost when new Vm requested for that location.

It's meaningful if you have multiple Location&Providers (regions), but it confuses first timers who have single Location&Provides (region).

**Comment by ozgune** [comment]
We recently changed our UI flow for the managed service and open source users. Open source users can now use a script to cloudify their bare metal instances - https://github.com/ubicloud/ubicloud/pull/333

That change makes this flow more intuitive. With that, I'm closing this issue. (cc @enescakir )
