### ISSUE TITLE
Building docker images for different platforms

### ISSUE THREAD

**Issue by enescakir** [ubicloud/ubicloud#138]
ARM based machines become popular lately. Thanks to Apple M1/M2 processors, `linux/amd64` is not enough anymore. `linux/arm64`  docker image is a must for popular open source projects.

We are using [docker/build-push-action](https://github.com/docker/build-push-action) action for building and pushing Docker Hub. Also it supports building for `linux/arm64`.

But GitHub Action runners are slow for building for `linux/arm64` because they are not ARM based machines. Building pipeline duration's increased from ~3mins (only `linux/amd64`) to ~22mins (`linux/amd64` and `linux/arm64`). It's okay for now.

We may consider different options to build our images.
- Use [Docker Hub Builds](https://docs.docker.com/docker-hub/builds/)
- We were using custom larger Intel/ARM EC2 machines for running our GitHub Action build pipelines at my previous company. https://github.com/marketplace/actions/on-demand-self-hosted-aws-ec2-runner-for-github-actions
- Use a powerful VM on a hosted ubicloud platform as runner. Also, it may help to catch some bugs at production.

**Comment by fdr** [comment]
I've been meaning to get Hetzner Altra computers into the mix, and we need to build firmware as well. As I mentioned 804f0555228f34da5cf5b0344ce3a431af108ef1, the current situation is a bit...rudimentary.
