### ISSUE TITLE
Is this or how is it comparable to maas.io?

### ISSUE THREAD

**Issue by haneef95** [ubicloud/ubicloud#1384]
Referring to this: https://maas.io/

**Comment by fdr** [comment]
Looks to me like we could potential platform on a maas-hosted service. maas handles things like pxe boot, wheras we rely on these kind of things to do out of-band machine wipes and things of that nature. maas has some virtualization features but seems to spend most of its front page real-estate and words on things that are one level "below" us in the stack. It has, tucked in a few corners, some stuff about virtualization (where it supports multiple hypervisors at integration targets, much as openstack does), whereas ubicloud is currently a virtualization-focused system, with no bare metal component. 

All in all, it looks like there are areas of overlap, but it's one level "lower."
