### ISSUE TITLE
Add a created_at column to the payment methods table

### ISSUE THREAD

**Issue by enescakir** [ubicloud/ubicloud#1691]

**Comment by fsd-niraj** [comment]
Can you provide some more details on this?

**Comment by enescakir** [comment]
Hi @fsd-niraj, the project billing page has a list of payment methods. When a project has multiple payment methods, it can be difficult to determine which one was added first. Adding an extra column to display the creation date could be useful. The `PaymentMethod` model already includes a `created_at` column, we just need to display this on the UI.


<img width="1222" alt="Screenshot 2024-07-04 at 17 00 47" src="https://github.com/ubicloud/ubicloud/assets/993199/f1f670d2-65bf-4c3a-bcb7-2ee731d6b17d">

**Comment by fsd-niraj** [comment]
Sure I can start working on this one, also can you assign it to me on github please

**Comment by byucesoy** [comment]
Hi @fsd-niraj, I assigned this issue to you.

**Comment by fsd-niraj** [comment]
Hey, Apologies to get back after this long.
I am having this "service "db-migrator" didn't complete successfully: exit 1" error while I try to compose the docker.
Do you have any quick solution for this so that I can quickly move to the bug.

**Comment by enescakir** [comment]
> Hey, Apologies to get back after this long. I am having this "service "db-migrator" didn't complete successfully: exit 1" error while I try to compose the docker. Do you have any quick solution for this so that I can quickly move to the bug.

Hi @fsd-niraj, did it display a specific error? It's challenging to identify the issue with a generic error message. We highly recommend setting up a local Ruby environment for development. We have a guide available for this
https://github.com/ubicloud/ubicloud/blob/main/DEVELOPERS.md

**Comment by ttfra** [comment]
Since no update has been posted here for last 3 weeks, I assume there is no ongoing work on this. If that's the case, I can take this on.

**Comment by fsd-niraj** [comment]
Hi, Please go ahead, I am a little occupied these days.
Thanks
