### ISSUE TITLE
Documentation discrepancy in README.md

### ISSUE THREAD

**Issue by abramche** [ubicloud/ubicloud#1904]
> We're currently in public beta.

> Ubicloud is in public alpha

It would be good to align the discrepancy to which is closer to truth 🙂

**Comment by ozgune** [comment]
Hi @abramche - Thank you for bringing this to our attention!

We decided to update our status to public beta once we crossed one hundred customers on our managed platform, but missed this occurrence. I just opened a pull request to make things consistent: https://github.com/ubicloud/ubicloud/pull/1908

(cc @enescakir )

**Comment by ozgune** [comment]
Merged the fix to our readme.md. @abramche - thanks again for reporting this!
