### ISSUE TITLE
Problems when having ubuntu-latest as fallback option

### ISSUE THREAD

**Issue by marcelmedeiros1** [ubicloud/ubicloud#2391]
When we try to define ubuntu-latest as our fallback option, the workload never executes.
`runs-on: [ubicloud-standard-2, ubuntu-latest]`

But.. When we define the runs-on with the ubicloud runners only, everything executes fine:
`runs-on: ubicloud-standard-2`

**Comment by enescakir** [comment]
Hi Marcel,

Github does not have array syntax to specify fallback option. When you specify an array of labels, jobs will be queued on runners that have all the labels that you specify, but Ubicloud runners have only one of these labels (the first one). You can read more about this at [here](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/using-self-hosted-runners-in-a-workflow#about-self-hosted-runner-labels).

If you want to run the same job on multiple runners with different sizes, you can use the matrix feature in Github Actions. For the record, this is not fallback but more like running the job twice.

```yml
    strategy:
      matrix:
        runner: [ubicloud, ubicloud-standard-8]
```
