### ISSUE TITLE
YYY comments

### ISSUE THREAD

**Issue by pykello** [ubicloud/ubicloud#342]
## Web
- need a better way to manage coupling of routes and erbs 
 - [ ] required at launch
 - [x] not required at launch
https://github.com/ubicloud/ubicloud/blob/ab84bf6b5096bb4e1cf2772c0ae3bb8a6f07a9a7/views/vm/create.erb#L21
https://github.com/ubicloud/ubicloud/blob/ab84bf6b5096bb4e1cf2772c0ae3bb8a6f07a9a7/views/project/create.erb#L10
- Should password secret and session secret be the same? Are there rotation issues? 
 - [ ] required at launch
 - [x] not required at launch
https://github.com/ubicloud/ubicloud/blob/ab84bf6b5096bb4e1cf2772c0ae3bb8a6f07a9a7/clover_web.rb#L172-L176

## Clover
- Implement a robust mesh networking concurrency algorithm.
 - [ ] required at launch
 - [x] not required at launch
https://github.com/ubicloud/ubicloud/blob/ab84bf6b5096bb4e1cf2772c0ae3bb8a6f07a9a7/prog/vm/nexus.rb#L277
- Hack to deal with the presentation currently being in "vcpu" which has a pretty specific meaning being ambigious tothreads or actual cores.
 - [ ] required at launch
 - [x] not required at launch
https://github.com/ubicloud/ubicloud/blob/ab84bf6b5096bb4e1cf2772c0ae3bb8a6f07a9a7/model/vm.rb#L47-L61
- inhost names
 - [ ] required at launch
 - [x] not required at launch
https://github.com/ubicloud/ubicloud/blob/ab84bf6b5096bb4e1cf2772c0ae3bb8a6f07a9a7/model/vm.rb#L143-L147
- Use database jsonb prepend
 - [ ] required at launch
 - [x] not required at launch
https://github.com/ubicloud/ubicloud/blob/ab84bf6b5096bb4e1cf2772c0ae3bb8a6f07a9a7/prog/base.rb#L145-L149

## Rhizome
- Check checksums
 - [ ] required at launch
 - [x] not required at launch
https://github.com/ubicloud/ubicloud/blob/ab84bf6b5096bb4e1cf2772c0ae3bb8a6f07a9a7/rhizome/bin/prep_host.rb#L8-L9
- Handle customer images
 - [ ] required at launch
 - [x] not required at launch
https://github.com/ubicloud/ubicloud/blob/ab84bf6b5096bb4e1cf2772c0ae3bb8a6f07a9a7/rhizome/lib/vm_setup.rb#L530-L533
- systemd capabilities
 - [ ] required at launch
 - [x] not required at launch
https://github.com/ubicloud/ubicloud/blob/ab84bf6b5096bb4e1cf2772c0ae3bb8a6f07a9a7/rhizome/lib/vm_setup.rb#L573-L576
- systemd escaping
 - [ ] required at launch
 - [x] not required at launch
https://github.com/ubicloud/ubicloud/blob/ab84bf6b5096bb4e1cf2772c0ae3bb8a6f07a9a7/rhizome/lib/vm_setup.rb#L595-L597
- ~~static guest mac~~
 - Fixed by #349
https://github.com/ubicloud/ubicloud/blob/ab84bf6b5096bb4e1cf2772c0ae3bb8a6f07a9a7/rhizome/lib/vm_setup.rb#L640-L649

## Tests
- Hacked up to pretend Ampere Altras have hyperthreading for demonstration on small metal instances.
 - [ ] required at launch
 - [x] not required at launch
https://github.com/ubicloud/ubicloud/blob/ab84bf6b5096bb4e1cf2772c0ae3bb8a6f07a9a7/spec/model/vm_spec.rb#L94-L95

**Comment by furkansahin** [comment]
https://github.com/ubicloud/ubicloud/pull/349 will fix the guest_mac YYY

**Comment by enescakir** [comment]
Most of them are no longer an issue or have been resolved.
