### ISSUE TITLE
Issues with login names

### ISSUE THREAD

**Issue by pykello** [ubicloud/ubicloud#454]
**Problem 1**
Users can choose login name, but after the VM is created we don't display it anywhere.
1. Should we display it in VM details page?
2. Maybe just force "ubi"?

In either case, what about providing a connect command, similar to what Azure did?

**Problem 2**
I used "root" for unix user when creating the VM. It happily accepted it, and the VM went it to running state.
1. I couldn't log into it
2. I even couldn't ping it.

**Comment by enescakir** [comment]
Do you have any VM on Azure? What's the connect command for a VM? Maybe `ssh USER@IP_ADDRESS`?

Long connection string is useful for database services, but not sure for the vms. But agree with displaying unix user on details page.

**Comment by pykello** [comment]
@enescakir here is an screenshot:

![image](https://github.com/ubicloud/ubicloud/assets/628106/b5e75fa3-782b-4467-b9f5-f3d7d3d6d0aa)
