### ISSUE TITLE
API Reference Widget Not Redirecting in Dashboard

### ISSUE THREAD

**Issue by madebywelch** [ubicloud/ubicloud#466]
In the Dashboard view of Ubicloud, I noticed that the "API Reference" widget does not seem to function properly. When I click on it, it does not redirect to the intended page or provide any response.

Steps to reproduce:

Open Ubicloud and navigate to the Dashboard view.
Locate the "API Reference" widget.
Click on the widget.
Expected behavior:
After clicking the widget, I expect it to redirect to the corresponding API documentation page.

Actual behavior:
Clicking the widget does not result in any action or redirection.

**Comment by enescakir** [comment]
Thanks for reporting it. We don't have public API documentation yet. I forgot broken link there. I replaced this widget at #467. When we have API documentation, I will add it to console again.

**Comment by ianaya89** [comment]
Hey @enescakir is there any reference/docs for the Public API. I love what you created and I am interested on working in possible IaC integrations (Terraform, Pulimi, SDK, etc).

**Comment by enescakir** [comment]
> Hey @enescakir is there any reference/docs for the Public API. I love what you created and I am interested on working in possible IaC integrations (Terraform, Pulumi, SDK, etc).

@ianaya89, Thanks for your interest. Currently, we don't have an official API documentation. We are working on our APIs at the moment. Soon, we will have the preview version.
We have some endpoints but they are under heavy development by @velioglu 
https://github.com/ubicloud/ubicloud/tree/main/routes/api
