### ISSUE TITLE
Project naming collide with established brand.

### ISSUE THREAD

**Issue by ArKam** [ubicloud/ubicloud#478]
Hi folks,

just a message to warn you that you MAY infringe one of Ubisoft brands property or risk legal action from Ubisoft as they already have a public and private cloud named ubicloud since around 2008.

I would highly suggest an alternative name that would not risk any infringement or legal action but that would still weight your idea such as omnicloud.

**Comment by jcubic** [comment]
There are more things named Ubicloud when you Google the name and I don't think Ubisoft is on the list: https://www.google.com/search?hl=en&q=Ubicloud. It's hard to tell.

**Comment by bot66** [comment]
lol, ubisoft :potato: potato server.
