### ISSUE TITLE
Docker containers can't resolve DNS addresses

### ISSUE THREAD

**Issue by enescakir** [ubicloud/ubicloud#507]
When I tried to run GitHub action that builds docker image on our self-hosted runners, it failed with following error:

> ERROR: failed to solve: ruby:3.2.2-alpine3.17: failed to do request:
Head
"https://registry-1.docker.io/v2/library/ruby/manifests/3.2.2-alpine3.17":
dial tcp: lookup registry-1.docker.io on 192.168.0.1:53: read udp
172.17.0.2:48484->192.168.0.1:53: i/o timeout
https://github.com/ubicloud/ubicloud/actions/runs/5969312670/job/16194950769

Even simple `docker run -it alpine:3:17 ping google.com` can't resolve DNS.

`/etc/resolve.conf` of VmHost and Vm
```
nameserver 127.0.0.53
options edns0 trust-ad
search .
```

`/etc/resolve.conf` of docker container
```
nameserver 192.168.111.192
search .
```

We debug it with @furkansahin.
It has some possible solutions:
- Add DNS config to docker daemon config
    - Add following to `/etc/docker/daemon.json`, then restart docker `sudo systemctl restart docker`
```json
{
    "dns": ["9.9.9.9"]
}
```

- Docker gets `resolve.conf` content from `systemd-resolved` service. We can add additional DNS records to it. Also Digital Ocean has `/etc/systemd/resolved.conf.d/DigitalOcean.conf` config.
```bash
sudo mkdir /etc/systemd/resolved.conf.d
sudo sh -c 'echo "[Resolve]\nDNS=9.9.9.9" > /etc/systemd/resolved.conf.d/Ubicloud.conf'
sudo systemctl restart systemd-resolved.service
```

I added `Ubicloud.conf` to our self-hosted runners. But we need to fix this issue for new virtual machines too. Running docker containers on new created vm without any additional config is good user experience.

**Comment by fdr** [comment]
what does `resolvectl` say?

**Comment by fdr** [comment]
Interesting, so, on the VM, dnsmasq absorbs queries for ipv4 but not for ipv6. May be something to smooth out one way or another.
