### ISSUE TITLE
Make UI improvements

### ISSUE THREAD

**Issue by ozgune** [ubicloud/ubicloud#60]
We could evaluate the following changes / improvements to our current UI. I'll defer writing tests to a separate issue.

* Theme color - We currently have this set to violet. Test with 2 shades of orange, 1 black, and another color
* Object storage - When you click on our S3-like service, instead of a "page not found", say that this service is under development
* "vm-host" page improvements
  * Do we need to have "Location" in this page? Isn't the idea that we can cloudify any host?
  * (don't know) Should we be more prescriptive to the user on how to give SSH access?
  * (don't know) Does Equinix also put the SSH keys under /root/.ssh?
  * This page asks hostname to enter. Do we expect a hostname, IP address, or either on this page?
* Make the Settings page nicer
* Terminology changes
  * CPU -> vCPU
  * Location -> Provider & Location
  * Virtual Machines -> Compute or Elastic Compute (Is Elastic Compute trademarked by AWS?)
* Dashboard (home page) -> The layout uses a table. Should we change this to separate buttons like OVH?

**Comment by enescakir** [comment]
I'm uploading previous image again because we renamed repository.
<img width="1370" alt="Screenshot 2023-05-15 at 18 57 34" src="https://github.com/ubicloud/ubicloud/assets/993199/93bc42c4-9c10-479e-ab2d-e585c0db9657">

**Comment by ozgune** [comment]
I'm uploading a banner to see if we can refer to it in our Readme.

![Ubicloud Sky Above The Clouds GitHub](https://github.com/ubicloud/ubicloud/assets/2545443/7bbb47ee-5690-4b06-87e7-89df545c9400)

**Comment by ozgune** [comment]
I'm uploading a slightly edited version of the above banner

![The Sky Above The Clouds](https://github.com/ubicloud/ubicloud/assets/2545443/c6b16994-6c0c-45c5-8fa5-dc2c02ca4e75)

**Comment by ozgune** [comment]
Third time is a charm

![Ubicloud Sky Above The Clouds GitHub v4](https://github.com/ubicloud/ubicloud/assets/2545443/3ced9942-8054-48e5-84b1-6ffabc05dc63)

**Comment by enescakir** [comment]
I'm uploading console screenshot that has orange theme to put our READEM.


<img width="1506" alt="add-vm-host-orange" src="https://github.com/ubicloud/ubicloud/assets/993199/b7d8badf-424b-4486-bc8d-0da8740f995c">

**Comment by ozgune** [comment]
I'm uploading several images that we use in the authorization design document.

![ABAC default tag names](https://github.com/ubicloud/ubicloud/assets/2545443/ae9adc83-0203-4584-ae62-80a7e830857a)
![ABAC design data model](https://github.com/ubicloud/ubicloud/assets/2545443/96f2138a-20e3-434a-9bb3-28350510c34e)
![ABAC example](https://github.com/ubicloud/ubicloud/assets/2545443/165799de-8b3c-4eff-a60f-d728c07f6c03)

**Comment by enescakir** [comment]
We don't have any open tasks from this issue. I'm closing it.

**Comment by ozgune** [comment]
![Screenshot 2023-08-16 at 10 14 44 AM](https://github.com/ubicloud/ubicloud/assets/2545443/fc06d75a-484a-4160-a803-97a591800b28)

**Comment by ozgune** [comment]
![Github Banner - Light](https://github.com/ubicloud/ubicloud/assets/2545443/3ce4d335-1275-461a-b167-af2633c06d58)

**Comment by ozgune** [comment]
![White mode - v1](https://github.com/ubicloud/ubicloud/assets/2545443/6c637365-93a2-4609-bd8e-4c6e4a4bf8f6)

**Comment by ozgune** [comment]
![Readme banner](https://github.com/ubicloud/ubicloud/assets/2545443/caa2d2be-26f3-4635-be78-1861886e2ebe)

**Comment by ozgune** [comment]
![Ubicloud Banner New - 2024-09](https://github.com/user-attachments/assets/70bf546e-3343-4f07-a530-a98e11f44a65)

**Comment by ozgune** [comment]
![ubi-github-image (1)](https://github.com/user-attachments/assets/779e73bd-c260-4729-8430-c630628f1b6b)
