### ISSUE TITLE
ping doesn't work on AlmaLinux 9.1

### ISSUE THREAD

**Issue by ozgune** [ubicloud/ubicloud#927]
I created an Ubuntu 22.04 and AlmaLinux 9.1 VM on the same bare metal instance using the console.

I then tried outgoing network connections. Ping on Ubuntu 22.04 works as expected.

<pre>
ubi@vmqs6r34:~$ ping www.google.com
PING www.google.com(arn11s04-in-x04.1e100.net (2a00:1450:400f:80b::2004)) 56 data bytes
64 bytes from arn11s04-in-x04.1e100.net (2a00:1450:400f:80b::2004): icmp_seq=1 ttl=57 time=8.61 ms
64 bytes from arn11s04-in-x04.1e100.net (2a00:1450:400f:80b::2004): icmp_seq=2 ttl=57 time=8.65 ms
64 bytes from arn11s04-in-x04.1e100.net (2a00:1450:400f:80b::2004): icmp_seq=3 ttl=57 time=8.70 ms
64 bytes from arn11s04-in-x04.1e100.net (2a00:1450:400f:80b::2004): icmp_seq=4 ttl=57 time=8.64 ms
^C
--- www.google.com ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 8.611/8.648/8.695/0.030 ms
</pre>

Traceroute on this instance didn't resolve. I don't know if this is expected.

<pre>
ozgun@Ozguns-MacBook-Air dev % traceroute www.google.com
traceroute to www.google.com (216.58.214.4), 64 hops max, 52 byte packets
 1  10.128.0.1 (10.128.0.1)  14.230 ms  10.461 ms  10.405 ms
 2  ams-eq6-cr1-v11.31173.se (185.65.134.65)  13.232 ms  11.865 ms  13.003 ms
 3  185.65.134.51 (185.65.134.51)  16.138 ms  11.448 ms  13.171 ms
 4  * * *
^C
</pre>

Then, I tried pinging Google on AlmaLinux 9.1. When I first tried, it didn't work for about 6-7 seconds.

<pre>
[ubi@vm1me2t5 ~]$ ping www.google.com
^C
</pre>

I then waited for longer and realized that each ping takes about 7-8 seconds. For some reason though, ping thinks that it's taking 8ms. Also, ping doesn't report any packet loss.

<pre>
[ubi@vm1me2t5 ~]$ ping www.google.com
PING www.google.com(arn09s19-in-x04.1e100.net (2a00:1450:400f:80c::2004)) 56 data bytes
64 bytes from arn09s19-in-x04.1e100.net (2a00:1450:400f:80c::2004): icmp_seq=1 ttl=116 time=8.06 ms
64 bytes from arn09s19-in-x04.1e100.net (2a00:1450:400f:80c::2004): icmp_seq=2 ttl=116 time=8.07 ms
64 bytes from arn09s19-in-x04.1e100.net (2a00:1450:400f:80c::2004): icmp_seq=3 ttl=116 time=8.07 ms
64 bytes from arn09s19-in-x04.1e100.net (2a00:1450:400f:80c::2004): icmp_seq=4 ttl=116 time=8.04 ms
^C64 bytes from 2a00:1450:400f:80c::2004: icmp_seq=5 ttl=116 time=8.06 ms

--- www.google.com ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 20083ms
rtt min/avg/max/mdev = 8.042/8.059/8.074/0.011 ms
</pre>

Here's the associated traceroute. This path looks pretty different than the Ubuntu VM's.

<pre>
[ubi@vm1me2t5 ~]$ traceroute www.google.com
traceroute to www.google.com (142.250.74.68), 30 hops max, 60 byte packets
 1  _gateway (192.168.148.128)  0.397 ms  0.357 ms  0.340 ms
 2  169.254.159.124 (169.254.159.124)  0.323 ms  0.306 ms  0.286 ms
 3  static.1.21.21.65.clients.your-server.de (65.21.21.1)  0.489 ms  0.472 ms  0.454 ms
 4  core32.hel1.hetzner.com (213.239.224.129)  0.436 ms  0.419 ms core31.hel1.hetzner.com (213.239.224.125)  0.397 ms
 5  core53.sto.hetzner.com (213.239.254.70)  6.865 ms core52.sto.hetzner.com (213.239.254.58)  6.847 ms core53.sto.hetzner.com (213.239.254.70)  6.830 ms
 6  core40.sto.hetzner.com (213.239.252.78)  19.283 ms core3.sto.hetzner.com (213.239.252.66)  6.883 ms  6.846 ms
 7  213-133-121-202.clients.your-server.de (213.133.121.202)  8.163 ms  8.146 ms 142.250.161.204 (142.250.161.204)  7.137 ms
 8  * * *
 9  142.251.48.40 (142.251.48.40)  7.202 ms  7.183 ms 142.250.239.184 (142.250.239.184)  7.163 ms
10  108.170.254.50 (108.170.254.50)  7.761 ms 108.170.254.34 (108.170.254.34)  7.704 ms arn09s23-in-f4.1e100.net (142.250.74.68)  7.107 ms
</pre>

**Comment by enescakir** [comment]
Did you tested it in Finland or Germany? @byucesoy reported experiencing high latency with the Finland vm host. Hetzner identified an issue with the NIC and replaced it today. This might be related.

**Comment by ozgune** [comment]
Both of these tests were done in Finland and at the same time. The Ubuntu VM worked and the AlmaLinux one didn't. So, I'm thinking this is unrelated to the underlying host.
